export const PRICE_VARIANT_REQUEST = "PRICE_VARIANT_REQUEST";
export const PRICE_VARIANT_SUCCESS = "PRICE_VARIANT_SUCCESS";
export const PRICE_VARIANT_FAIL = "PRICE_VARIANT_FAIL";
export const CLEAR_PRICE_VARIANT_ERROR = "CLEAR_PRICE_VARIANT_ERROR";